phones/api/urls.py
from django.urls import path
from . import views

app_name = "api"


urlpatterns = [
    path("phone/original", views.OriginalAPI.as_view(), name="Originals"),
    path("phone/nationality/<str:code>/", views.NationalityAPI.as_view(), name="Nationality"),

    path("phones/", views.PhoneAPI.as_view(), name="Phones_API"),
    path("brand/<str:code>", views.BrandsAPI.as_view(), name=""),

    path("auth/", views.AuthAPI.as_view(), name="auth"),
    path("register/", views.RegisterAPI.as_view(), name="register"),
]

phones/core/urls.py
from django.urls import path
from . import views

app_name = "core"


urlpatterns = [
    
    path("new_phone/", views.PhoneCreateView.as_view(), name="New_Phone_view"),
    path("auth/", views.AuthView.as_view(), name="auth"),
    path("register/", views.RegisterView.as_view(), name="register"),
    
    path("phones/", views.PhonesListView.as_view(), name="phones"),

    path("", views.index, name="index")

]

phones/phones/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.permissions import AllowAny

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

schema_view = get_schema_view(
    openapi.Info(
        title="Phone project",
        default_version="v1",
        description="Swagger API Documentation for the Project",
        contact=openapi.Contact(email="aminmasoudi2003+git@gmail.com"),
    ),
    public=True,
    permission_classes=(AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/", include("api.urls")),
    path("", include("core.urls")),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),

   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

phones/core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator# Create your models here.


class Country(models.Model):

    name = models.CharField(_("Country Name"), max_length=30, unique=True) 
    code = models.CharField(_("Country Code"), max_length=3, unique=True)   

    class Meta:
        verbose_name = _("Country")
        verbose_name_plural = _("Countries")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Country_detail", kwargs={"pk": self.pk})




class Brand(models.Model):

    name = models.CharField(_("Brand Name"), max_length=50, unique=True)
    country = models.ForeignKey("core.Country", verbose_name=_("Nationality"), on_delete=models.DO_NOTHING, related_name="+")
    

    class Meta:
        verbose_name = _("Brand")
        verbose_name_plural = _("Brands")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Brand_detail", kwargs={"pk": self.pk})




class Phone(models.Model):

    name = models.CharField(_("Model"), max_length=64, unique=True)
    brand = models.ForeignKey("core.Brand", to_field="name",  verbose_name=_("Brand"), on_delete=models.DO_NOTHING)
    price = models.PositiveIntegerField(_("Price"))
    color = models.CharField(_("Color"), max_length=50)
    #FIXME What if two color of a Phone??
    size = models.FloatField(_("Display size"), validators=[
        MinValueValidator(0, message='Value must be greater than or equal to 0.'),
    ])
    quantity = models.PositiveIntegerField(_("Quantity"))
    built = models.ForeignKey("core.Country", to_field="name", verbose_name=_("Made IN"), on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name = _("Phone")
        verbose_name_plural = _("Mobile Phones")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Phone_detail", kwargs={"pk": self.pk})

    @property
    def nationality(self):
        return self.brand.country.name 
    @property
    def exist(self):
        return self.quantity >= 0

phones/api/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

from django.http import HttpResponseRedirect
from rest_framework.generics import ListCreateAPIView, ListAPIView
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from .serializers import (
    PhoneSerializer,
    LoginSerializer,
    RegisterSerializer,
    BrandSerializer
)
from core.models import Phone, Brand, Country
from . import utils




class AuthAPI(APIView):

    def post(self, request, format=None):
        login_ser = LoginSerializer(User, data=request.data)
        login_ser.is_valid(raise_exception=True)
        user = authenticate(request,
                            username=login_ser.validated_data.get("username"),
                            password=login_ser.validated_data.get("password"))
        if user:
            login(request, user)
            return Response(login_ser.validated_data.get("username"))
        return Response({
            "detail": "failed to log in"
        }, 401)

class RegisterAPI(APIView):

    def post(self, request, format=None):
        register_ser = RegisterSerializer(data=request.data)
        register_ser.is_valid(raise_exception=True)
        user = register_ser.save()
        login(request ,user)
        return Response(register_ser.validated_data)


class PhoneAPI(ListCreateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = Phone.objects.all()
    serializer_class = PhoneSerializer
    


class BrandsAPI(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = BrandSerializer

    def get(self, request, code):
        country = Country.objects.filter(code=code).first()
        if country :
            brands = Brand.objects.filter(country=country.pk).all()
            brands = BrandSerializer(brands, many=True)
            return Response(brands.data)

class OriginalAPI(APIView):
    permission_classes = [IsAuthenticated]
    serializer_class = BrandSerializer

    def get(self, request, *args, **kwargs):
        phones = Phone.objects.all()
        phones = list(filter(
            lambda x: utils.filter_by_nationality(x),
            phones
        ))
        phones = PhoneSerializer(phones, many=True)        
        return Response(phones.data)
    

class NationalityAPI(APIView):
    serializer_class = PhoneSerializer
    permission_classes = [IsAuthenticated]

    def get(self, request, *args, **kwargs):
        country_code = kwargs["code"]
        country = Country.objects.filter(code=country_code).first()
        phones = Phone.objects.all()
        phones = list(filter(
            lambda x: utils.filter_by_nationality(x, country.name),
            phones
        ))
        phones = PhoneSerializer(phones, many=True)        
        return Response(phones.data)

phones/core/views.py
from django.views.generic import TemplateView, CreateView, ListView
from django.urls import reverse_lazy
from .models import Phone
from django.http import HttpResponseRedirect
class NewPhoneView(TemplateView):
    template_name = "core/phones.html"

class AuthView(TemplateView):
    template_name = "core/auth.html"
    extra_context = {
        'api' : reverse_lazy('api:auth')
    }


class RegisterView(TemplateView):
    template_name = "core/register.html"
    extra_context = {
        'api' : reverse_lazy('api:register')
    }


class PhoneCreateView(CreateView):
    model = Phone
    template_name = "core/new_phone.html"
    fields= "__all__"


class PhonesListView(ListView):
    model = Phone
    template_name = "core/phones_list.html"


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse_lazy("core:phones"))
    return HttpResponseRedirect(reverse_lazy("core:auth"))

phones/core/templates/core/auth.html
{% extends 'core/base.html' %}

{% block title %}Auth{% endblock title %}

{% block main %}
<form id="form">
    <div class="mb-3">
        <input name="username" class="form-control mx-auto w-auto" autocomplete="off" autofocus  id="username" placeholder="Username" type="text">
    </div>
    <div class="mb-3">
        <input name="password" class="form-control mx-auto w-auto" autocomplete="off" autofocus  id="password" placeholder="password" type="password">
    </div>
    <button class="btn btn-primary" type="submit">Log In</button>
</form>
{% load static %}

<script src="{% static 'js/auth.js' %}"></script>
{% endblock main %}

phones/core/templates/core/base.html
<!DOCTYPE html>

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
        <!-- http://getbootstrap.com/docs/5.1/ -->
        <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
        <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"></script>

        
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>

        <nav class="bg-light border navbar navbar-expand-md navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <span class="blue">P</span>
                    <span class="red">h</span>
                    <span class="yellow">o</span>
                    <span class="green">n</span> 
                    <span class="blue">e</span> 
                </a>
  
            </div>
        </nav>
        <header></header>

        <main class="container py-5 text-center">
            {% block main %}{% endblock %}
        </main>
    </body>
    </html>

phones/core/templates/core/new_phone.html
{% extends 'core/base.html' %}

{% block title %}Add a new phone{% endblock title %}


{% block main %}

<style>
    .form{
        display: inline-grid;
    }
    input{
        margin: 1rem;
    }
</style>


<form class="form" action="{% url 'api:Phones_API' %}" method="post">
    {% csrf_token %}
    <label for="name">Name: </label>
    <input type="text" name="name" id="name">

    <label for="brand">Brand: </label>
    <input type="text" name="brand" id="brand">

    <label for="price">Price</label>
    <input type="number" name="price" id="price">

    <label for="color">Color</label>
    <input type="text" name="color" id="color">

    <label for="size">Size</label>
    <input type="number" name="size" id="size">


    <input type="number" name="quantity" id="quantity" placeholder="Quantity">
    <input type="text" name="built" id="built" placeholder="Made in">
    <input type="submit" value="Add">

</form>

{% endblock main %}

phones/core/templates/core/phones.html
{% extends 'core/base.html' %}

{% block title %}Add a new phone{% endblock title %}


{% block body %}

<style>
    .form{
        display: inline-grid;
    }
    input{
        margin: 2rem;
    }
</style>


<form class="form" action="/api/add_phone/" method="post">
    <label for="name">Name: </label>
    <input type="text" name="name" id="name">
    <label for="brand">Brand: </label>
    <input type="text" name="brand" id="brand">
    <input type="number" name="price" id="price">
    <input type="text" name="color" id="color">
    <input type="number" name="size" id="size">
    <input type="number" name="quantity" id="quantity" placeholder="Quantity">
    <input type="text" name="build" id="build" placeholder="Made in">
    <input type="submit" value="Add">

</form>

{% endblock body %}

phones/core/templates/core/phones_list.html
{% extends 'core/base.html' %}

{% block title %}Phones{% endblock title %}

{% block main %}


<table class="table">
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col"> Exist</th>

    </tr>
    {% for phone in object_list %}
    <tr>
        <td scope="row">{{phone.id}}</td>
        <td>{{phone.name}}</td>
        <td>{{phone.exist}}</td>
    </tr>
    {% endfor %}

</table>

{% endblock main %}

phones/core/templates/core/register.html
{% extends 'core/base.html' %}

{% block title %}Register{% endblock title %}

{% block main %}
<form id="form">
    <div class="mb-3">
        <input name="username" class="form-control mx-auto w-auto" autocomplete="off" autofocus  id="username" placeholder="Username" type="text">
    </div>
    <div class="mb-3">
        <input name="password" class="form-control mx-auto w-auto" autocomplete="off" autofocus  id="password" placeholder="password" type="password">
    </div>
    <div class="mb-3">
        <input name="password2" class="form-control mx-auto w-auto" autocomplete="off" autofocus  id="password2" placeholder="password again" type="password">
    </div>
    <button class="btn btn-primary" type="submit">Register</button>
</form>
{% load static %}
<script>
    let api = '{{api}}'
    let csrf = '{{ csrf_token }}'
</script>
<script src="{% static 'js/register.js' %}"></script>
{% endblock main %}